### ISSUE TITLE
Upgraded Issues

### ISSUE THREAD

**Issue by kwlayman** [fredsted/webhook.site#51]
I upgraded and now I can't see all my requests on the left like I could in the regular version. I see you have links now to navigate thru entries but the Next-> link is not working so I have to go all the way back to end and start over moving back thru.

Please give option to list all on left like unpaid version.

**Comment by fredsted** [comment]
Hi @kwlayman Thanks for reporting this. I've made a temporary fix that shows the first 500 requests instead of the first 50 until I have some time to fix it later today.

**Comment by kwlayman** [comment]
Thanks. My browser only shows one request on left after upgradeOn Feb 21, 2019 2:10 AM, Simon Fredsted <notifications@github.com> wrote:Hi @kwlayman Thanks for reporting this. I've made a temporary fix that shows the first 500 requests instead of the first 50 until I have some time to fix it later today.

**Comment by fredsted** [comment]
Hi again @kwlayman I think the issue is due to the fact that I forgot to include a "Previous Page" button in the request sidebar list, which means you were viewing the very last page that might only have contained a few requests. Now you should be able to go back and view the previous ones without changing the URL. Sorry for the inconvenience!

**Comment by kwlayman** [comment]
yes working as expected now, thx!
